name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache ~/.cabal/packages and ~/.cabal/store
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}
      - uses: actions/checkout@v2
      - run: make init
      - run: make test
